// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrgqPJv5XSKtDA8icB5NiSmJOj1cqVNY',
    appId: '1:18460469919:android:a1b0a08d0573562c3c50aa',
    messagingSenderId: '18460469919',
    projectId: 'alkaramh-847d4',
    storageBucket: 'alkaramh-847d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq8lgUO6IZ0VEegQoL9BqzH7zkpFUBV_g',
    appId: '1:18460469919:ios:88b48aef239843133c50aa',
    messagingSenderId: '18460469919',
    projectId: 'alkaramh-847d4',
    storageBucket: 'alkaramh-847d4.firebasestorage.app',
    androidClientId: '18460469919-03qlhbfg2aidd5i62g3e4o8didcqqmrh.apps.googleusercontent.com',
    iosClientId: '18460469919-f6p5qp0eo4atccqqguch649svrfpfmeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.alkaramh',
  );

}